// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9lRHEEwRgFxYpRd3UXtDQQqwwkyyXhCg',
    appId: '1:195886261942:web:a0fdc873ad6e3f4c892817',
    messagingSenderId: '195886261942',
    projectId: 'ayojana-hub',
    authDomain: 'ayojana-hub.firebaseapp.com',
    storageBucket: 'ayojana-hub.firebasestorage.app',
    measurementId: 'G-GH7ZREVPT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNsT247gr92P71P8TVUxUkJovaUHSG09o',
    appId: '1:195886261942:android:e238e141c192bc6b892817',
    messagingSenderId: '195886261942',
    projectId: 'ayojana-hub',
    storageBucket: 'ayojana-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuiT8qkIT-htUq3jjvuY8YuYVsLg_px9E',
    appId: '1:195886261942:ios:f550bf6a036e492d892817',
    messagingSenderId: '195886261942',
    projectId: 'ayojana-hub',
    storageBucket: 'ayojana-hub.firebasestorage.app',
    iosBundleId: 'com.example.ayojanahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuiT8qkIT-htUq3jjvuY8YuYVsLg_px9E',
    appId: '1:195886261942:ios:f550bf6a036e492d892817',
    messagingSenderId: '195886261942',
    projectId: 'ayojana-hub',
    storageBucket: 'ayojana-hub.firebasestorage.app',
    iosBundleId: 'com.example.ayojanahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9lRHEEwRgFxYpRd3UXtDQQqwwkyyXhCg',
    appId: '1:195886261942:web:94ebe026bc0da4a1892817',
    messagingSenderId: '195886261942',
    projectId: 'ayojana-hub',
    authDomain: 'ayojana-hub.firebaseapp.com',
    storageBucket: 'ayojana-hub.firebasestorage.app',
    measurementId: 'G-MLH1YNH3SB',
  );

}